version: "3.8"  # Recommended version for compatibility

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=""  # Empty password for root user
      - MYSQL_DATABASE=stationSki
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes  # Allow empty password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    restart: unless-stopped
    networks:
      - devops_network

  gestionski:
    image: http://192.168.33.10:8081/repository/gestionski/${IMAGE_NAME}:${IMAGE_TAG}
    container_name: gestionski
    ports:
      - "8089:8089"
    restart: unless-stopped
    volumes:
      - ./logs:/logs
    depends_on:
      - mysqldb  # Ensure mysqldb is up before gestionski starts
    networks:
      - devops_network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8083:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped
    networks:
      - devops_network

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8081:8081"
    environment:
      - NEXUS_CONTEXT_PATH=/nexus
    volumes:
      - nexus_data:/nexus-data
    restart: unless-stopped
    networks:
      - devops_network

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "9000:9000"
    restart: unless-stopped
    networks:
      - devops_network

volumes:
  jenkins_home:
  nexus_data:
  mysql_data:  # Ensure persistence for MySQL data

networks:
  devops_network:
    driver: bridge
