
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8083:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - devops_network

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8081:8081"
    environment:
      - NEXUS_CONTEXT_PATH=/nexus
    volumes:
      - nexus_data:/nexus-data
    networks:
      - devops_network

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - devops_network

volumes:
  jenkins_home:
  nexus_data:

networks:
  devops_network:
    driver: bridge
