global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-app'
    static_configs:
      - targets: ['mahmoud-devops:8089']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql:3306']
